// client_react/src/elements/RegisterForm/RegisterForm.jsx
import React, { useState } from 'react'
import "./RegisterForm.css"
import SubmitButton from '../Buttons/SubmitButton/SubmitButton'
import RegisterSuccess from '../RegisterSuccess/RegisterSuccess'
import Form from '../../components/Form/Form'

const RegisterForm = (props) => {
  const [showRegister, setShowRegister] = useState(true)
  const [formData, setFormData] = useState(null)

  const [isLoading, setIsLoading] = useState(false)
  const [emailError, setEmailError] = useState(false)
  const [usernameError, setUsernameError] = useState(false)

  const hadleFormData = (prev, event) => {
    let value = event.target.value
    if (value == null) value = ""
    return { ...prev, ...{[event.target.name]: value}}
  }
  const handleInput = (event) => setFormData(prev => hadleFormData(prev, event))

  const handleSubmit = async (event) => {

    event.preventDefault()
    setIsLoading(true)
    const headers = {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "mode": "cors"
    }
    if (!isLoading) {
      try {
        const res = await fetch(
          "/api/user/register",
          {
            method: "POST",
            headers: headers,
            body: JSON.stringify(formData)
          }
        )
        const resJson = await res.json()
        
        //shows result of registration
        if (resJson) {
          setIsLoading(false)
          if (!resJson.error) setShowRegister(false)
          if (resJson.message == "USER_ALREADY_EXISTS") {}
          if (resJson.message == "COULD_NOT_ADD_USER") {}
        }
      } catch (err) {}
    }
  }

  if (showRegister) {
    return (
      <Form handleSubmit={handleSubmit}>
        <h1>Registrieren</h1>
        <div className='app__input-wrapper'>
          <input
            placeholder='Email'
            required
            name="email"
            type="email"
            onChange={handleInput}
          />
        </div>
        <div className='app__input-wrapper'>
          <input
            placeholder='Benutzername'
            id='register-username-input'
            required
            name="username"
            type="text"
            onChange={handleInput}
          />
        </div>
        <div className='app__input-wrapper'>
          <input
            placeholder='Passwort'
            id='register-password-input'
            required
            name="password"
            type="password"
            onChange={handleInput}
          />
        </div>
      </Form>
    )
  } else {
    return <RegisterSuccess />
  }
}
export default RegisterForm

// client_svelte/src/lib/Form/RegisterForm.svelte
<Form
    title="Registrieren"
    action={submit}
>
    <Input
        placeholder='Email'
        name="email"
        type="email"
        value={email}
        errorMessage={emailError}
    />
    <Input
        placeholder='Benutzername'
        name="username"
        type="text"
        value={username}
        errorMessage={usernameError}
    />
    <Input
        placeholder='Passwort'
        name="password"
        type="password"
        value={password}
        errorMessage={passwordError}
    />
    <SubmitButton />
</Form>

<script>
    import { get, writable } from "svelte/store";
    import SubmitButton from "$lib/buttons/SubmitButton.svelte"
    import Form from "$lib/Form/Form.svelte";
    import Input from "$lib/Form/Input.svelte"

    let success = false

    let email = writable("")
    let username = writable("")
    let password = writable("")

    let emailError = "" /* "Email existiert bereits!" */
    let usernameError = "" /* "Benutzername vergeben!" */
    let passwordError = "" /* "Falsches Passwort!" */
    
    let firstRender = true
    const unsubEmail = email.subscribe((v) => {
        if (firstRender) return
        emailError = ""
    })
    const unsubPassword = password.subscribe((v) => {
        if (firstRender) return
        passwordError = ""
    })
    const unsubUsername = username.subscribe((v) => {
        if (firstRender) return
        usernameError = ""
    })
    firstRender = false

    async function submit(e) {
        e.preventDefault()
        const res = await fetch(
            "/api/user/register",
            {
                method: "POST",
                headers: {
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                    "mode": "cors"
                },
                body: JSON.stringify({
                    password: get(password),
                    username: get(username),
                    email: get(email)
                })
            }
        ).then(res => res.json())
        
        console.log(res)
        if (!res.error) {
            success = true
        } else {

        }
    }
</script>
